// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// scaled_Ztildex_maker
arma::mat scaled_Ztildex_maker(arma::sp_mat& alpha, const arma::colvec& res_z, const arma::colvec& res_d);
RcppExport SEXP _OutcomeWeights_scaled_Ztildex_maker(SEXP alphaSEXP, SEXP res_zSEXP, SEXP res_dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type res_z(res_zSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type res_d(res_dSEXP);
    rcpp_result_gen = Rcpp::wrap(scaled_Ztildex_maker(alpha, res_z, res_d));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OutcomeWeights_scaled_Ztildex_maker", (DL_FUNC) &_OutcomeWeights_scaled_Ztildex_maker, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_OutcomeWeights(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
