# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scaled_Ztildex_maker <- function(alpha, res_z, res_d) {
    .Call(`_OutcomeWeights_scaled_Ztildex_maker`, alpha, res_z, res_d)
}

